kdc:
  image: hadoop-krb:2.7.4
  hostname: kdc
  container_name: kdc
  domainname: hadoop
  net: hadoop
  volumes:
    - ${HADOOP_COMPOSE_DIR}/kerberos/krb5kdc:/var/lib/krb5kdc
    - ${HADOOP_COMPOSE_DIR}/kerberos/logs:/var/log/kerberos

namenode:
  image: hadoop-nn:2.7.4
  hostname: namenode
  container_name: namenode
  domainname: hadoop
  net: hadoop
  volumes:
    - ${HADOOP_COMPOSE_DIR}/config:/etc/hadoop
    - ${HADOOP_COMPOSE_DIR}/logs:/var/log/hadoop/logs
    - ${HADOOP_COMPOSE_DIR}/storage/namenode:/tmp/hadoop-root/dfs/name
    - ${HADOOP_COMPOSE_DIR}/kerberos/krb5kdc:/var/lib/krb5kdc
  ports:
    - "50070:50070"
    - "50470:50470"
    - "8020:8020"
  environment:
    - FORMAT_NAMENODE=${FORMAT_NAMENODE}

datanode1:
  image: hadoop-dn:2.7.4
  hostname: datanode1
  container_name: datanode1
  domainname: hadoop
  net: hadoop
  volumes:
    - ${HADOOP_COMPOSE_DIR}/config:/etc/hadoop
    - ${HADOOP_COMPOSE_DIR}/logs:/var/log/hadoop/logs
    - ${HADOOP_COMPOSE_DIR}/storage/datanode1:/tmp/hadoop-root/dfs/data
    - ${HADOOP_COMPOSE_DIR}/kerberos/krb5kdc:/var/lib/krb5kdc
  ports:
    - "50010:50010"

datanode2:
  image: hadoop-dn:2.7.4
  hostname: datanode2
  container_name: datanode2
  domainname: hadoop
  net: hadoop
  volumes:
    - ${HADOOP_COMPOSE_DIR}/config:/etc/hadoop
    - ${HADOOP_COMPOSE_DIR}/logs:/var/log/hadoop/logs
    - ${HADOOP_COMPOSE_DIR}/storage/datanode2:/tmp/hadoop-root/dfs/data
    - ${HADOOP_COMPOSE_DIR}/kerberos/krb5kdc:/var/lib/krb5kdc
  ports:
    - "50011:50010"

datanode3:
  image: hadoop-dn:2.7.4
  hostname: datanode3
  container_name: datanode3
  domainname: hadoop
  net: hadoop
  volumes:
    - ${HADOOP_COMPOSE_DIR}/config:/etc/hadoop
    - ${HADOOP_COMPOSE_DIR}/logs:/var/log/hadoop/logs
    - ${HADOOP_COMPOSE_DIR}/storage/datanode3:/tmp/hadoop-root/dfs/data
    - ${HADOOP_COMPOSE_DIR}/kerberos/krb5kdc:/var/lib/krb5kdc
  ports:
    - "50012:50010"

resourcemanager:
  image: hadoop-rm:2.7.4
  hostname: resourcemanager
  container_name: resourcemanager
  domainname: hadoop
  net: hadoop
  volumes:
    - ${HADOOP_COMPOSE_DIR}/config:/etc/hadoop
    - ${HADOOP_COMPOSE_DIR}/logs:/opt/hadoop/hadoop-dist/target/hadoop-2.7.4/logs
    - ${HADOOP_COMPOSE_DIR}/kerberos/krb5kdc:/var/lib/krb5kdc
  ports:
    - "8030:8030"
    - "8031:8031"
    - "8032:8032"
    - "8033:8033"
    - "8088:8088"
    - "8090:8090"

nodemanager1:
  image: hadoop-nm:2.7.4
  hostname: nodemanager1
  container_name: nodemanager1
  domainname: hadoop
  net: hadoop
  volumes:
    - ${HADOOP_COMPOSE_DIR}/config:/etc/hadoop
    - ${HADOOP_COMPOSE_DIR}/logs:/opt/hadoop/hadoop-dist/target/hadoop-2.7.4/logs
    - ${HADOOP_COMPOSE_DIR}/kerberos/krb5kdc:/var/lib/krb5kdc
  ports:
    - "8042:8042"

nodemanager2:
  image: hadoop-nm:2.7.4
  hostname: nodemanager2
  container_name: nodemanager2
  domainname: hadoop
  net: hadoop
  volumes:
    - ${HADOOP_COMPOSE_DIR}/config:/etc/hadoop
    - ${HADOOP_COMPOSE_DIR}/logs:/opt/hadoop/hadoop-dist/target/hadoop-2.7.4/logs
    - ${HADOOP_COMPOSE_DIR}/kerberos/krb5kdc:/var/lib/krb5kdc
  ports:
    - "8043:8042"

hive:
  image: hadoop-hive:2.7.4
  hostname: hive
  container_name: hive
  domainname: hadoop
  net: hadoop
  volumes:
    - ${HADOOP_COMPOSE_DIR}/config:/etc/hadoop
    - ${HADOOP_COMPOSE_DIR}/config:/etc/hive
    - ${HADOOP_COMPOSE_DIR}/kerberos/krb5kdc:/var/lib/krb5kdc

spark:
  image: hadoop-spark:2.7.4
  hostname: spark
  container_name: spark
  domainname: hadoop
  net: hadoop
  volumes:
    - ${HADOOP_COMPOSE_DIR}/config:/etc/hadoop
    - ${HADOOP_COMPOSE_DIR}/config:/etc/hive
    - ${HADOOP_COMPOSE_DIR}/kerberos/krb5kdc:/var/lib/krb5kdc
    - ${HADOOP_COMPOSE_DIR}/files:/root/files
  ports:
    - "8008:8008"
    - "8998:8998"
